import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { BookOpen, Clock3, GraduationCap, Star } from "lucide-react";
import { Container, Section } from "@/components/layout";
import { VerifiedBadge } from "@/components/verified-badge";
import { CourseEnroll } from "@/components/course-enroll";
import { CourseReviewForm } from "@/components/course-review-form";
import { getPublicCourse } from "@/lib/courses";
import { createClient } from "@/lib/supabase/server";
export const dynamic="force-dynamic";
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const data=await getPublicCourse(slug);if(!data)return {title:"Course not found",robots:{index:false,follow:false}};return {title:data.course.title,description:data.course.short_description,alternates:{canonical:`/courses/${data.course.slug}`},openGraph:{title:data.course.title,description:data.course.short_description,images:data.course.thumbnail?[data.course.thumbnail]:[]}};}
export default async function CourseDetail({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;const data=await getPublicCourse(slug);if(!data)notFound();const {course,modules,lessons,reviews}=data;
 const db=await createClient();const {data:{user}}=await db.auth.getUser();const {data:enrollment}=user?await db.from("enrollments").select("id").eq("user_id",user.id).eq("course_id",course.id).maybeSingle():{data:null};
 return <Section className="min-h-[65vh] bg-[#f3f3ec]"><Container><Link href="/courses" className="eyebrow">← All courses</Link><div className="mt-6 grid gap-10 lg:grid-cols-[1.4fr_.8fr]">
  <div><p className="eyebrow">{course.level} · {course.language}</p><h1 className="mt-3 text-4xl sm:text-5xl">{course.title}</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-muted-foreground">{course.short_description}</p><div className="mt-6 flex flex-wrap items-center gap-3"><Link href={`/${course.instructor_username}`} className="font-medium underline underline-offset-4">{course.instructor_name}</Link>{course.instructor_verified&&<VerifiedBadge/>}<span className="text-sm text-muted-foreground">· {course.duration_text}</span><span className="inline-flex items-center gap-1 text-sm"><Star className="size-4 fill-[#dcae45] text-[#dcae45]"/>{course.average_rating??"New"}{course.review_count?` (${course.review_count})`:""}</span></div>
   <section className="mt-10 rounded-2xl border bg-background p-6"><h2 className="text-2xl">What you’ll learn</h2><p className="mt-4 whitespace-pre-wrap text-sm leading-7">{course.description}</p></section>
   <section className="mt-8"><h2 className="text-3xl">Course curriculum</h2><p className="mt-2 text-sm text-muted-foreground">{modules.length} modules · {course.total_minutes} minutes of lessons</p><div className="mt-5 space-y-4">{modules.map((module,i)=><details key={module.id} className="rounded-xl border bg-background p-5" open={i===0}><summary className="cursor-pointer font-semibold">{i+1}. {module.title}</summary><ul className="mt-4 space-y-3 text-sm">{lessons.filter(l=>l.module_id===module.id).map(lesson=><li key={lesson.id} className="rounded-lg bg-[#f7f6ef] p-4"><div className="flex justify-between gap-3"><span>{lesson.title}{lesson.is_preview&&<span className="ml-2 text-xs font-semibold text-primary">Preview</span>}</span><span className="text-xs text-muted-foreground">{lesson.duration_minutes?`${lesson.duration_minutes} min`:lesson.type}</span></div>{lesson.is_preview&&<div className="mt-3 space-y-2">{lesson.content&&<p className="whitespace-pre-wrap leading-6 text-muted-foreground">{lesson.content}</p>}{lesson.video_url&&<a className="underline" href={lesson.video_url} target="_blank" rel="noreferrer">Watch preview ↗</a>}{lesson.attachment_url&&<a className="ml-4 underline" href={lesson.attachment_url} target="_blank" rel="noreferrer">Open reading ↗</a>}</div>}</li>)}</ul></details>)}</div></section>
   <section className="mt-10"><h2 className="text-3xl">Learner reviews</h2><div className="mt-4 space-y-3">{reviews.map((r,i)=><article className="rounded-xl border bg-background p-5" key={`${r.created_at}-${i}`}><p className="font-medium">{r.learner_name} · {"★".repeat(r.rating)}</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{r.comment}</p></article>)}{!reviews.length&&<p className="rounded-xl border bg-background p-5 text-sm text-muted-foreground">Reviews from enrolled learners will appear here.</p>}</div>{enrollment&&<div className="mt-5"><CourseReviewForm courseId={course.id}/></div>}</section>
  </div><aside className="h-fit rounded-2xl border bg-background p-5 lg:sticky lg:top-6">{course.thumbnail?<Image src={course.thumbnail} alt="" width={800} height={480} unoptimized className="mb-5 max-h-64 w-full rounded-lg object-cover"/>:<div className="mb-5 flex h-40 items-center justify-center rounded-lg bg-[#e7eadf]"><BookOpen className="size-12 text-primary"/></div>}<p className="font-display text-4xl">{course.price===0?"Free":`₹${course.price.toLocaleString("en-IN")}`}</p><div className="my-5 space-y-3 text-sm text-muted-foreground"><p className="flex gap-2"><Clock3 size={17}/> {course.duration_text}</p><p className="flex gap-2"><GraduationCap size={17}/> {course.learner_count} learners enrolled</p></div><CourseEnroll courseId={course.id} slug={course.slug} title={course.title} price={course.price} enrolled={Boolean(enrollment)} razorpayKeyId={process.env.NEXT_PUBLIC_RAZORPAY_KEY_ID}/><p className="mt-4 text-xs leading-5 text-muted-foreground">All courses are reviewed by our team. Course completion certificates are verifiable by their unique code.</p></aside></div></Container></Section>;
}
